### ISSUE TITLE
Support for arrow functions

### ISSUE THREAD

**Issue by Kuzmin** [autoric/nject#17]
Trying to use arrow functions for the "factory function" crashes with the following stack trace:

```
2015-12-04T17:22:17.411221+00:00 app[worker.1]:   var dependencies = argDecl[1].split(FN_ARG_SPLIT);
2015-12-04T17:22:17.411217+00:00 app[worker.1]: /app/node_modules/nject/lib/nject.js:84
2015-12-04T17:22:17.411223+00:00 app[worker.1]:
2015-12-04T17:22:17.411222+00:00 app[worker.1]:                             ^
2015-12-04T17:22:17.411224+00:00 app[worker.1]: TypeError: Cannot read property '1' of null
2015-12-04T17:22:17.411225+00:00 app[worker.1]:     at Tree._findDependencies (/app/node_modules/nject/lib/nject.js:84:29)
2015-12-04T17:22:17.411226+00:00 app[worker.1]:     at Tree.register (/app/node_modules/nject/lib/nject.js:298:25)
2015-12-04T17:22:17.411227+00:00 app[worker.1]:     at Object.<anonymous> (/app/server/config/config.js:61:9)
2015-12-04T17:22:17.411227+00:00 app[worker.1]:     at Module._compile (module.js:425:26)
2015-12-04T17:22:17.411228+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:432:10)
2015-12-04T17:22:17.411230+00:00 app[worker.1]:     at Function.Module._load (module.js:311:12)
2015-12-04T17:22:17.411229+00:00 app[worker.1]:     at Module.load (module.js:356:32)
2015-12-04T17:22:17.411230+00:00 app[worker.1]:     at Module.require (module.js:366:17)
2015-12-04T17:22:17.411231+00:00 app[worker.1]:     at require (module.js:385:17)
2015-12-04T17:22:17.411233+00:00 app[worker.1]:     at Array.reduce (native)
2015-12-04T17:22:17.411232+00:00 app[worker.1]:     at /app/node_modules/node-require-directory/index.js:28:29
2015-12-04T17:22:17.411234+00:00 app[worker.1]:     at module.exports.require_directory (/app/node_modules/node-require-directory/index.js:11:38)
2015-12-04T17:22:17.411234+00:00 app[worker.1]:     at /app/node_modules/node-require-directory/index.js:17:37
2015-12-04T17:22:17.411235+00:00 app[worker.1]:     at Array.reduce (native)
2015-12-04T17:22:17.411236+00:00 app[worker.1]:     at module.exports.require_directory (/app/node_modules/node-require-directory/index.js:11:38)
2015-12-04T17:22:17.411237+00:00 app[worker.1]:     at Object.<anonymous> (/app/load-deps.js:9:1)
```

Not really unexpected if you know how the dependency injection is done, but thought I'd file a bug about this nonetheless.

**Comment by autoric** [comment]
@Kuzmin What version of nject are you running. Support for arrow functions was added in 2.0.1.

Can you please make sure you are running the latest, and if it still appears to not work correctly, can you please provide a simple test case that shows your issue?  Thanks!

**Comment by erin-noe-payne** [comment]
Haven't heard any updates, considering this issue closed.

**Comment by Kuzmin** [comment]
Yeah, I updated the dependency and it resolved the issue. Sorry, I thought I got back to you!

Thank you for your work!
